config/routes.rb
Rails.application.routes.draw do
  resources :answers
  resources :questions
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :question
  has_many :votes, dependent: :destroy
  enum status: { banned: 0, proposed: 1, accepted:2 }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  has_many :answers, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :question_tags, dependent: :destroy
end

app/models/question_tag.rb
class QuestionTag < ApplicationRecord
  belongs_to :tag
  belongs_to :question
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :question_tags, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  has_many :votes, dependent: :destroy
  has_many :answers, dependent: :destroy
  has_many :questions, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :question, optional: true
  belongs_to :answer, optional: true

  enum selection: { negative: 0, positive: 1 }
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: [:show, :edit, :update, :destroy]

  # GET /answers
  # GET /answers.json
  def index
    @answers = Answer.all
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
  end

  # GET /answers/new
  def new
    @answer = Answer.new
  end

  # GET /answers/1/edit
  def edit
  end

  # POST /answers
  # POST /answers.json
  def create
    @answer = Answer.new(answer_params)

    respond_to do |format|
      if @answer.save
        format.html { redirect_to @answer, notice: 'Answer was successfully created.' }
        format.json { render :show, status: :created, location: @answer }
      else
        format.html { render :new }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answers/1
  # PATCH/PUT /answers/1.json
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to @answer, notice: 'Answer was successfully updated.' }
        format.json { render :show, status: :ok, location: @answer }
      else
        format.html { render :edit }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to answers_url, notice: 'Answer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:status, :body, :user_id, :question_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name,:last_name])
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:title, :body, :user_id)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/answers/_form.html.haml
= form_for @answer do |f|
  - if @answer.errors.any?
    #error_explanation
      %h2= "#{pluralize(@answer.errors.count, "error")} prohibited this answer from being saved:"
      %ul
        - @answer.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :status
    = f.number_field :status
  .field
    = f.label :body
    = f.text_area :body
  .field
    = f.label :user
    = f.text_field :user
  .field
    = f.label :question
    = f.text_field :question
  .actions
    = f.submit 'Save'

app/views/answers/edit.html.haml
%h1 Editing answer

= render 'form'

= link_to 'Show', @answer
\|
= link_to 'Back', answers_path

app/views/answers/index.html.haml
%h1 Listing answers

%table
  %thead
    %tr
      %th Status
      %th Body
      %th User
      %th Question
      %th
      %th
      %th

  %tbody
    - @answers.each do |answer|
      %tr
        %td= answer.status
        %td= answer.body
        %td= answer.user
        %td= answer.question
        %td= link_to 'Show', answer
        %td= link_to 'Edit', edit_answer_path(answer)
        %td= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Answer', new_answer_path

app/views/answers/new.html.haml
%h1 New answer

= render 'form'

= link_to 'Back', answers_path

app/views/answers/show.html.haml
%p#notice= notice

%p
  %b Status:
  = @answer.status
%p
  %b Body:
  = @answer.body
%p
  %b User:
  = @answer.user
%p
  %b Question:
  = @answer.question

= link_to 'Edit', edit_answer_path(@answer)
\|
= link_to 'Back', answers_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title HackOverflow
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/questions/_form.html.haml
= form_for @question do |f|
  - if @question.errors.any?
    #error_explanation
      %h2= "#{pluralize(@question.errors.count, "error")} prohibited this question from being saved:"
      %ul
        - @question.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :body
    = f.text_area :body
  .field
    = f.label :user
    = f.text_field :user
  .actions
    = f.submit 'Save'

app/views/questions/edit.html.haml
%h1 Editing question

= render 'form'

= link_to 'Show', @question
\|
= link_to 'Back', questions_path

app/views/questions/index.html.haml
%h1 Listing questions

%table
  %thead
    %tr
      %th Title
      %th Body
      %th User
      %th
      %th
      %th

  %tbody
    - @questions.each do |question|
      %tr
        %td= question.title
        %td= question.body
        %td= question.user
        %td= link_to 'Show', question
        %td= link_to 'Edit', edit_question_path(question)
        %td= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Question', new_question_path

app/views/questions/new.html.haml
%h1 New question

= render 'form'

= link_to 'Back', questions_path

app/views/questions/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @question.title
%p
  %b Body:
  = @question.body
%p
  %b User:
  = @question.user

= link_to 'Edit', edit_question_path(@question)
\|
= link_to 'Back', questions_path